### ISSUE TITLE
Char is non-blittable in .NET

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/TestWinRT#14]
Should move the char field from Blittable to NonBlittable

**Comment by kennykerr** [comment]
Is this documentation correct?

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/sizeof

It says that `bool` is 1 byte and `char` is 2 bytes. That is consistent with WinRT and thus should make both C# `bool` and `char` blittable.

**Comment by Scottj1s** [comment]
They're actually non-blittable at run time.  GCHandle.Alloc fails to pin a non-blittable type, including a struct with a char field:

struct char_struct
{
    public char c;
}
char_struct cs = new char_struct() { c = 'a' };
// following throws System.ArgumentException: 'Object contains non-primitive or non-blittable data. (Parameter 'value')'
var handle = GCHandle.Alloc(cs, GCHandleType.Pinned);

**Comment by kennykerr** [comment]
Seems like that should work. Anyway, happy to move `char` but that doesn't seem intentional.

**Comment by Scottj1s** [comment]
Thanks.  Note that blittability is not just about same size, but also same representation.  And char can convert to either Unicode or ANSI (with Windows always using Unicode - other platforms may differ).

https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types

**Comment by kennykerr** [comment]
Thanks, that's the link I was looking for.
