### ISSUE TITLE
CI loop only builds, doesn't run test

### ISSUE THREAD

**Issue by asklar** [microsoft/TestWinRT#48]
The CI pipeline builds Test.sln, but a) it's using old versions of cppwinrt and b) it doesn't actually run any of the tests
It would be good to run the tests here

**Comment by kennykerr** [comment]
I tried updating the nuget version but I hit mysterious nuget/msbuild errors. Unfortunately, this project isn't aging well and needs a lot of work to get back into good shape. I can't even get it to build anymore as is.
