### ISSUE TITLE
TestWinRT will crash when used from CppWinRT

### ISSUE THREAD

**Issue by asklar** [microsoft/TestWinRT#49]
the testwinrt code has this test:
```cpp
void Collection4Call(Collection4Handler const& handler)
{
    IMapView<hstring, hstring> a = single_threaded_map_view<hstring, hstring>(std::map<hstring, hstring>{ {L"apples", L"1"}, { L"oranges",L"2" }, { L"pears",L"3" } });
    IMapView<hstring, hstring> b;
    IMapView<hstring, hstring> c = handler(a, b);
    TEST_REQUIRE_N(L"Collection", 4, a != b && a != c);
    TEST_REQUIRE_N(L"Collection", 4, std::equal(begin(a), end(a), begin(b), end(b)));
    TEST_REQUIRE_N(L"Collection", 4, std::equal(begin(a), end(a), begin(c), end(c)));

    TEST_REQUIRE_N(L"Collection", 4, c.Lookup(L"apples") == L"1");
    TEST_REQUIRE_N(L"Collection", 4, c.HasKey(L"oranges"));
    IMapView<hstring, hstring> d;
    IMapView<hstring, hstring> e;
    c.Split(d, e);
    TEST_REQUIRE_N(L"Collection", 4, d.Size() && e.Size());
}
```

However, IMapSplitView<K,V>.Split() is broken in cppwinrt and just nulls out d and e, which will make the TEST_REQUIRE_N at the end fail.

We would need a way to disable this test for cppwinrt

**Comment by kennykerr** [comment]
`Split` is not broken in C++/WinRT. That method is not required to do anything and C++/WinRT has implemented it that way from the start. It is simply an ill-conceived method that should not have made it into the interface. If the test validates that it does something other than return `null` values then the test is wrong. If other language projections implement it then they should be fixed to return `null` values.

**Comment by asklar** [comment]
@Scottj1s @ujjwalchadha sounds like cswinrt might need to be fixed to no-op Split?

**Comment by kennykerr** [comment]
By the way, C++/CX and C++/WinRT implement Split the same way and .NET doesn't even expose this method.
